# Feature: As a Gmail user, I want to be able to navigate to landing page so that I can check email

#   @Gmail @run1
#   Scenario: Customer is displayed with Gmail.com landing page
#     Given I am on the Gail portal
#     When I click on "Login"
#     Then I should see "LoginHeader"

#  @Gmail @GmailLoginin
#   Scenario: User is displayed with Gmail.com landing page and tries to login into the portal
#     Given I am on the Gmail portal
#     And I enter the inputs for login
#     And I click on "LoginBtn"
#     Then I should see "errorMessage"

#   @Gmail @GmailForgetpassword
#   Scenario: User is displayed with Forget Password link
#     Given I am on the Gmail portal
#     And I enter the inputs for login
#     And I click on "LoginBtn"
#     Then I should see Forgot Password link  

#   @Gmail @Gmailsignup
#   Scenario: User is displayed with signup link
#     Given I am on the Gmail portal
#     And I enter the inputs for login
#     And I click on "LoginBtn"
#     Then I should see signup link